# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlogExercise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BlogExercise

  target 'BlogExerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BlogExerciseUITests' do
    # Pods for testing
  end

end
